require "config.ale"
require "config.compe"
require "config.dashboard"
-- require "config.formatter" TODO eventually
require "config.fterm"
require "config.trouble"
require "config.bufferline"
require "config.gitsigns"
require "config.indent-blankline"
require "config.lspinstall"
require "config.lualine"
require "config.nvim-tree"
require "config.telescope"
require "config.treesitter"
require "config.vim-better-whitespace"
require "config.vim-test"
